# Generated by Django 4.0.2 on 2022-02-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('topic', models.CharField(max_length=258)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('exp_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('published', 'published'), ('exp', 'exp'), ('deleted', 'deleted')], max_length=30)),
                ('comment', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ManyToManyField(to='account.ProfileStudent')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profileteacher')),
            ],
        ),
    ]
